services:
  api:
    build: .
    container_name: isf_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

      rabbitmq:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ws:
    build: .

    container_name: isf_ws

    command: uvicorn app.workers.websocket.main:app --host 0.0.0.0 --port 8001

    ports:
      - "8001:8001"

    env_file:
      - .env

    volumes:
      - .:/app

    depends_on:
      rabbitmq:
        condition: service_healthy

      db:
        condition: service_healthy


  event_worker:
    build: .
    container_name: isf_event_worker

    command: python -m app.workers.event_worker.main

    env_file:
      - .env

    volumes:
      - .:/app

    depends_on:
      rabbitmq:
        condition: service_healthy

      db:
        condition: service_healthy

  celery:
    build: .
    container_name: isf_celery

    command: celery -A app.workers.celery.app:celery_app worker --loglevel=info

    env_file:
      - .env

    volumes:
      - .:/app

    depends_on:
      rabbitmq:
        condition: service_healthy

      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: isf_db
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: isf_rabbit
    hostname: ${RABBIT__HOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT__LOGIN}
      RABBITMQ_DEFAULT_PASS: ${RABBIT__PASSWORD}
    healthcheck:
        test: ["CMD", "rabbitmq-diagnostics", "check_running"]
        interval: 10s
        timeout: 5s
        retries: 5
volumes:
  postgres_data: