"""

Revision ID: 098d5dfd25b2
Revises: b7554841cae2
Create Date: 2026-08-17 15:22:24.023674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098d5dfd25b2'
down_revision: Union[str, Sequence[str], None] = 'b7554841cae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('browser', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('browser_version', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('os', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('device_type', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('language', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('screen_width', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('screen_height', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('dpr', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('accuracy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'accuracy')
    op.drop_column('sessions', 'state')
    op.drop_column('sessions', 'city')
    op.drop_column('sessions', 'country')
    op.drop_column('sessions', 'dpr')
    op.drop_column('sessions', 'screen_height')
    op.drop_column('sessions', 'screen_width')
    op.drop_column('sessions', 'language')
    op.drop_column('sessions', 'timezone')
    op.drop_column('sessions', 'device_type')
    op.drop_column('sessions', 'os')
    op.drop_column('sessions', 'browser_version')
    op.drop_column('sessions', 'browser')
    # ### end Alembic commands ###
