"""

Revision ID: 2aad458b8160
Revises: 8a713b154782
Create Date: 2026-08-17 22:28:23.726417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aad458b8160'
down_revision: Union[str, Sequence[str], None] = '8a713b154782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'reporter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'reporter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
