"""

Revision ID: 86d29f5389f4
Revises: 2aad458b8160
Create Date: 2026-08-20 22:31:55.879339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d29f5389f4'
down_revision: Union[str, Sequence[str], None] = '2aad458b8160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('issues', sa.Column('closed_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'issues', 'users', ['closed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'closed_by_id')
    op.drop_column('issues', 'closed_at')
    # ### end Alembic commands ###
