"""

Revision ID: 98d56b946560
Revises: 656647d1b5dc
Create Date: 2026-09-22 19:41:37.615427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98d56b946560'
down_revision: Union[str, Sequence[str], None] = '656647d1b5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'status',
               existing_type=postgresql.ENUM('OPEN', 'IN_PROGRESS', 'REVIEW', 'DONE', 'CLOSED', name='issuestatus'),
               type_=sa.Enum('open', 'in_progress', 'review', 'done', 'closed', name='issue_status'),
               existing_nullable=False)
    op.alter_column('issues', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issuepriority'),
               type_=sa.Enum('low', 'medium', 'high', 'critical', name='issue_priority'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('issues', 'priority',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='issue_priority'),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issuepriority'),
               existing_nullable=False)
    op.alter_column('issues', 'status',
               existing_type=sa.Enum('open', 'in_progress', 'review', 'done', 'closed', name='issue_status'),
               type_=postgresql.ENUM('OPEN', 'IN_PROGRESS', 'REVIEW', 'DONE', 'CLOSED', name='issuestatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
