"""

Revision ID: c4fe91a98e4c
Revises: c5e86ccc1e91
Create Date: 2026-10-02 15:03:26.109557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4fe91a98e4c'
down_revision: Union[str, Sequence[str], None] = 'c5e86ccc1e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('replies_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'replies_count')
    # ### end Alembic commands ###
