"""

Revision ID: df790f6b10d9
Revises: 98d56b946560
Create Date: 2026-09-23 19:28:34.163131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df790f6b10d9'
down_revision: Union[str, Sequence[str], None] = '98d56b946560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    outbox_status = sa.Enum(
        'pending',
        'published',
        'failed',
        name='outbox_status',
    )

    outbox_status.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        'outbox_events',
        'status',
        existing_type=sa.VARCHAR(length=20),
        type_=outbox_status,
        postgresql_using='status::outbox_status',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outbox_events', 'status',
               existing_type=sa.Enum('pending', 'published', 'failed', name='outbox_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
