from enum import Enum


class ErrorCode(str, Enum):
    # base
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    BAD_REQUEST = "BAD_REQUEST"

    # auth
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN_TYPE = "INVALID_TOKEN_TYPE"
    REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND"

    # session
    SESSION_EXPIRED = "SESSION_EXPIRED"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_REVOKED = "SESSION_REVOKED"

    # user
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_NOT_ACTIVE = "USER_NOT_ACTIVE"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    USERNAME_TAKEN = "USERNAME_TAKEN"
    USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND"


    # email
    INVALID_EMAIL_CODE = "INVALID_EMAIL_CODE"
    EMAIL_CODE_EXPIRED = "EMAIL_CODE_EXPIRED"

    # password
    INVALID_RESET_CODE = "INVALID_RESET_CODE"
    RESET_CODE_EXPIRED = "RESET_CODE_EXPIRED"
    PASSWORD_INVALID = "PASSWORD_INVALID"

    # common
    PERMISSION_DENIED = "PERMISSION_DENIED"
    CONFLICT = "CONFLICT"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"