from enum import Enum


class ErrorCode(str, Enum):
    # Common
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    BAD_REQUEST = "BAD_REQUEST"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    CONFLICT = "CONFLICT"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS"
    INTERNAL_ERROR = "INTERNAL_ERROR"


    # Authentication
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN_TYPE = "INVALID_TOKEN_TYPE"
    REFRESH_TOKEN_NOT_FOUND = "REFRESH_TOKEN_NOT_FOUND"
    USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND"
    PASSWORD_INVALID = "PASSWORD_INVALID"


    # Session
    SESSION_EXPIRED = "SESSION_EXPIRED"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_REVOKED = "SESSION_REVOKED"


    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_NOT_ACTIVE = "USER_NOT_ACTIVE"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    USERNAME_TAKEN = "USERNAME_TAKEN"


    # Email
    INVALID_EMAIL_VERIFY_CODE = "INVALID_EMAIL_CODE"
    INVALID_EMAIL_RESET_CODE = "INVALID_EMAIL_RESET_CODE"
    EMAIL_VERIFIED_ALREADY = "EMAIL_VERIFIED_ALREADY"
    NEW_EMAIL_SAME = "NEW_EMAIL_SAME"


    # Password
    INVALID_PASSWORD_RESET_CODE = "INVALID_RESET_CODE"
    INVALID_PASSWORD_RESET_TOKEN = "INVALID_PASSWORD_RESET_TOKEN"
    NEW_PASSWORD_SAME = "NEW_PASSWORD_SAME"